Repository ieris19/SEP4-5X-Cloud, pull requests merged in 2023-05, with the labels that each got.

#2 Web API
  src/main/java/dk/via/sep4/cloud/Persistance/SensorReading.java
  src/main/java/dk/via/sep4/cloud/web/service/WebController.java
  src/main/java/dk/via/sep4/cloud/web/service/WebJSONData.java
  src/main/java/dk/via/sep4/cloud/web/service/WebRepository.java
  src/main/resources/application.properties
  src/test/java/dk/via/sep4/cloud/web/service/WebControllerTest.java
Labels: enhancement

#15 Data
  pom.xml
  src/main/java/dk/via/sep4/cloud/data/DBapplication.java
  src/main/java/dk/via/sep4/cloud/data/DBrepository.java
  src/main/java/dk/via/sep4/cloud/data/SensorReading.java
Labels: enhancement

#17 Updated one dependency
  pom.xml
Labels: bug

#21 Downlink stuff
  src/main/java/dk/via/sep4/cloud/data/SensorLimits.java
  src/main/java/dk/via/sep4/cloud/lorawan/LorawanSocketListener.java
  src/main/java/dk/via/sep4/cloud/lorawan/PayloadHandler.java
Labels: enhancement

#20 Testing Pipeline Action
  pom.xml
Labels: enhancement, help wanted

#28 Fix Sensor Reading parsing Timestamps
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorReading.java
Labels: bug

#38 Fix Date parsing on retrival
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorReading.java
Labels: bug

#55 New API Endpoints
  data/src/main/java/dk/via/sep4/cloud/data/DataRepository.java
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorLimits.java
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorReading.java
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorState.java
  data/src/main/java/dk/via/sep4/cloud/data/repository/MongoRepository.java
  data/src/test/java/dk/via/sep4/cloud/data/repository/ActiveMongoRepositoryTest.java
  web/src/main/java/dk/via/sep4/cloud/web/data/WebJSONData.java
  web/src/main/java/dk/via/sep4/cloud/web/data/WebRepository.java
  web/src/main/java/dk/via/sep4/cloud/web/service/WebController.java
Labels: enhancement

#56 Added Sensor State to Downlink message
  lorawan/src/main/java/dk/via/sep4/cloud/lorawan/websocket/DataHandler.java
  lorawan/src/main/java/dk/via/sep4/cloud/lorawan/websocket/WebsocketHandler.java
Labels: enhancement

#58 Fixing API
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorReading.java
  data/src/main/java/dk/via/sep4/cloud/data/repository/MongoRepository.java
  web/api-doc.md
  web/src/main/java/dk/via/sep4/cloud/web/data/WebRepository.java
  web/src/main/java/dk/via/sep4/cloud/web/service/WebController.java
  web/src/test/java/dk/via/sep4/cloud/web/service/ActiveRequestTest.java
  web/src/test/java/dk/via/sep4/cloud/web/service/HttpParser.java
  web/src/test/java/dk/via/sep4/cloud/web/service/HttpTestClient.java
  web/src/test/resources/dk/via/sep4/cloud/web/service/requestBodies
Labels: bug, enhancement

#59 Code cleanup
  data/pom.xml
  data/src/main/java/dk/via/sep4/cloud/data/DataConfiguration.java
  data/src/main/java/dk/via/sep4/cloud/data/DataRepository.java
  data/src/main/java/dk/via/sep4/cloud/data/dto/ControlState.java
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorLimits.java
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorReading.java
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorState.java
  data/src/main/java/dk/via/sep4/cloud/data/repository/MongoRepository.java
  data/src/test/java/dk/via/sep4/cloud/data/repository/ActiveMongoRepositoryTest.java
  lorawan/pom.xml
  lorawan/src/main/java/dk/via/sep4/cloud/lorawan/LorawanApplication.java
  lorawan/src/main/java/dk/via/sep4/cloud/lorawan/service/StatusController.java
  lorawan/src/main/java/dk/via/sep4/cloud/lorawan/websocket/LorawanClient.java
  lorawan/src/main/java/dk/via/sep4/cloud/lorawan/websocket/LorawanEventHandler.java
  lorawan/src/main/java/dk/via/sep4/cloud/lorawan/websocket/WebsocketHandler.java
  lorawan/src/main/java/dk/via/sep4/cloud/lorawan/websocket/utils/DataHandler.java
  lorawan/src/main/java/dk/via/sep4/cloud/lorawan/websocket/utils/WebSocketFactory.java
  web/api-doc.md
  web/pom.xml
  web/src/main/java/dk/via/sep4/cloud/web/data/WebRepository.java
  web/src/main/java/dk/via/sep4/cloud/web/service/WebController.java
  web/src/test/java/dk/via/sep4/cloud/web/service/ActiveRequestTest.java
Labels: bug, enhancement

#60 [HOTFIX] Fixed ErrorCode handling in the DB
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorReading.java
Labels: bug

#63 Added tests for some key features
  application/pom.xml
  data/src/main/java/dk/via/sep4/cloud/data/dto/ControlState.java
  data/src/main/java/dk/via/sep4/cloud/data/dto/JsonTransformable.java
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorLimits.java
  data/src/main/java/dk/via/sep4/cloud/data/dto/SensorReading.java
  data/src/main/java/dk/via/sep4/cloud/data/repository/DataOperationResult.java
  data/src/main/java/dk/via/sep4/cloud/data/repository/mongo/MongoOperationResult.java
  data/src/test/java/dk/via/sep4/cloud/data/dto/ControlStateTest.java
  data/src/test/java/dk/via/sep4/cloud/data/dto/JsonDTOTestable.java
  data/src/test/java/dk/via/sep4/cloud/data/dto/SensorLimitsTest.java
  data/src/test/java/dk/via/sep4/cloud/data/dto/SensorReadingTest.java
  data/src/test/java/dk/via/sep4/cloud/data/repository/MockData.java
  data/src/test/java/dk/via/sep4/cloud/data/repository/MockRepository.java
  data/src/test/java/dk/via/sep4/cloud/data/utils/JsonComparator.java
  lorawan/pom.xml
  lorawan/src/main/java/dk/via/sep4/cloud/lorawan/websocket/utils/DataHandler.java
  lorawan/src/test/java/dk/via/sep4/cloud/lorawan/websocket/utils/DataHandlerTest.java
  pom.xml
  web/pom.xml
  web/src/test/java/dk/via/sep4/cloud/web/data/MockRequest.java
  web/src/test/java/dk/via/sep4/cloud/web/data/WebRepositoryTest.java
  web/src/test/java/dk/via/sep4/cloud/web/net/ActiveRequestTest.java
  web/src/test/java/dk/via/sep4/cloud/web/net/HttpParser.java
  web/src/test/java/dk/via/sep4/cloud/web/net/HttpTestClient.java
Labels: enhancement

#64 Deployment workflow fixes
  .gcloud/lorawan-service-snapshot.yml
  .gcloud/web-service-snapshot.yml
  .github/workflows/google-cloud-deploy.yml
  .github/workflows/maven-test.yml
  .github/workflows/snapshot-deploy.yml
  .github/workflows/version-release.yml
  pom.xml
Labels: enhancement
